#!/usr/bin/env python3

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Table = pd.read_csv('/ufrc/zoo6927/share/Class_Files/data/CO-OPS__8729108__wl.csv')

#sample_data_table = FF.create_table(df.head())
#py.iplot(sample_data_table, filename='sample-data-table')


