#!/usr/bin/env python3

#open file
fhand = open('/ufrc/zoo6927/share/Class_Files/data/CO-OPS__8729108__wl.csv')


#assign variables
maxdiff = 0
prevline = 0

#for loop line by line
for line in fhand:

  columns = line.split(',') #make a list out of the dataset so each column becomes a part of $

  try:
    wl = float(columns[1]) #water level = convert turn the water level into column

  except:
    continue #account for header

  if prevline is not 0 and wl - prevline > maxdiff: #accounts for lines without entries and first entry; waterlevel entry minus previous line
    maxdiff = float(wl - prevline) #updates maxdiff value if waterlevel-previousline is greater than previous value
    date = (columns[0])
  prevline = wl #updates previous line each iteration

print ("Fastest Rise In Water Level:", maxdiff)
print ("Date and Time:", date)
