#!/usr/bin/env python3

import pandas as pd

#open file and turn into a nifty table
Table = pd.read_csv('/ufrc/zoo6927/share/Class_Files/data/CO-OPS__8729108__wl.csv')

#calculate the maximum water level
#df['Water Level'].max()

#print(Table.loc[Table[' Water Level'].idxmax()]) #prints the whole table 

print(Table.loc[Table[' Water Level'].idxmax(),['Date Time',' Water Level']]) 
#grab the row that has the maximum water level and display just the columns Date Time and Water Level
